/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package advanceddataminingproject;

import java.io.File;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author umit
 */
public class ADM_Main extends javax.swing.JFrame {
    FileOperations fileOperations;
    FileOperations fileOperations_suppliedtest;
    
    HashMap<String,Integer> valuesMap=new HashMap<>();
    HashMap<String,Integer> valuesMap_suppliedtest=new HashMap<>();
    List<String> hashmapkeys=new ArrayList<>();
    List<String> hashmapkeys_suppliedtest=new ArrayList<>();
    File fileopen,filetest;
    String[] ozellikListesi;
    List<String> veriler=new ArrayList<>();
    List<String> resultList=new ArrayList<>();
    List<String> veriler_suppliedTest=new ArrayList<>(); // supplied test seçili ise oradan gelen test verisi
    
    /**
     * Creates new form ADM_Main
     */
    public ADM_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadiGroup1 = new javax.swing.ButtonGroup();
        FileChooser_FileOpen = new javax.swing.JFileChooser();
        FileChooser_SuppliedTest = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        FileContentTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RadioButton_UseTrainingSet = new javax.swing.JRadioButton();
        RadioButton_UseSuppliedTest = new javax.swing.JRadioButton();
        RadioButton_CrossValidation = new javax.swing.JRadioButton();
        Button_UseSuppliedSetSelect = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Combox_ValueOfK = new javax.swing.JComboBox();
        Button_ClassifywithKNN = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Button_ClassifyNewData = new javax.swing.JButton();
        TextField_NewData = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextField_Result = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextField_SuccessRatio = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ozelliklerJList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListResults = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        Fold_Combobox = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        FileOpenMenu = new javax.swing.JMenuItem();
        FileExitMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileContentTextArea.setColumns(20);
        FileContentTextArea.setRows(5);
        FileContentTextArea.setFocusable(false);
        jScrollPane1.setViewportView(FileContentTextArea);

        jLabel2.setText("File Content:");

        jLabel1.setText("Attributes:");

        RadiGroup1.add(RadioButton_UseTrainingSet);
        RadioButton_UseTrainingSet.setSelected(true);
        RadioButton_UseTrainingSet.setText("Use Training Set");
        RadioButton_UseTrainingSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_UseTrainingSetActionPerformed(evt);
            }
        });

        RadiGroup1.add(RadioButton_UseSuppliedTest);
        RadioButton_UseSuppliedTest.setText("Use Supplied Test");
        RadioButton_UseSuppliedTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_UseSuppliedTestActionPerformed(evt);
            }
        });

        RadiGroup1.add(RadioButton_CrossValidation);
        RadioButton_CrossValidation.setText("Cross Validation");
        RadioButton_CrossValidation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_CrossValidationActionPerformed(evt);
            }
        });

        Button_UseSuppliedSetSelect.setText("Select ...");
        Button_UseSuppliedSetSelect.setEnabled(false);
        Button_UseSuppliedSetSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_UseSuppliedSetSelectMouseClicked(evt);
            }
        });

        jLabel3.setText("Value Of K:");

        Combox_ValueOfK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        Button_ClassifywithKNN.setText("Classify with KNN");
        Button_ClassifywithKNN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ClassifywithKNNMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Add New Data:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel5.setText("(There should be comma between attributes)");

        Button_ClassifyNewData.setText("Classify New Data");
        Button_ClassifyNewData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ClassifyNewDataMouseClicked(evt);
            }
        });

        jLabel6.setText("Classification Result:");

        jLabel7.setText("Classification Results:");

        jLabel8.setText("Success Ratio:");

        TextField_SuccessRatio.setEditable(false);
        TextField_SuccessRatio.setFont(new java.awt.Font("Times New Roman", 1, 33)); // NOI18N
        TextField_SuccessRatio.setForeground(new java.awt.Color(0, 153, 0));

        jScrollPane4.setViewportView(ozelliklerJList);

        jScrollPane2.setViewportView(JListResults);

        jLabel9.setText("Fold:");

        Fold_Combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15", "20" }));
        Fold_Combobox.setEnabled(false);

        FileMenu.setText("File");

        FileOpenMenu.setText("Open");
        FileOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileOpenMenuActionPerformed(evt);
            }
        });
        FileMenu.add(FileOpenMenu);

        FileExitMenu.setText("Exit");
        FileExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileExitMenuActionPerformed(evt);
            }
        });
        FileMenu.add(FileExitMenu);

        jMenuBar1.add(FileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RadioButton_UseTrainingSet)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(RadioButton_UseSuppliedTest)
                                                    .addComponent(RadioButton_CrossValidation))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(Fold_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(Button_UseSuppliedSetSelect))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 25, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(12, 12, 12)
                                        .addComponent(Combox_ValueOfK, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Button_ClassifywithKNN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_ClassifyNewData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextField_NewData, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextField_SuccessRatio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextField_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioButton_UseTrainingSet)
                                    .addComponent(jLabel3)
                                    .addComponent(Combox_ValueOfK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Button_UseSuppliedSetSelect)
                                            .addComponent(RadioButton_UseSuppliedTest))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RadioButton_CrossValidation)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Fold_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Button_ClassifywithKNN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextField_NewData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button_ClassifyNewData))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(TextField_SuccessRatio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButton_UseTrainingSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_UseTrainingSetActionPerformed
        Button_UseSuppliedSetSelect.setEnabled(false);
        Fold_Combobox.setEnabled(false);
    }//GEN-LAST:event_RadioButton_UseTrainingSetActionPerformed

    private void RadioButton_UseSuppliedTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_UseSuppliedTestActionPerformed
       Button_UseSuppliedSetSelect.setEnabled(true);
       Fold_Combobox.setEnabled(false);
    }//GEN-LAST:event_RadioButton_UseSuppliedTestActionPerformed

    private void RadioButton_CrossValidationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_CrossValidationActionPerformed
        Button_UseSuppliedSetSelect.setEnabled(false);
        Fold_Combobox.setEnabled(true);
    }//GEN-LAST:event_RadioButton_CrossValidationActionPerformed

    private void FileExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileExitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FileExitMenuActionPerformed

    private void FileOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileOpenMenuActionPerformed
        int returnVal = FileChooser_FileOpen.showOpenDialog(this);
        
        if (returnVal == FileChooser_FileOpen.APPROVE_OPTION) {
            fileopen=FileChooser_FileOpen.getSelectedFile();
            
            try{
                FileContentTextArea.read( new FileReader( fileopen.getAbsolutePath() ), null );
                fileOperations=new FileOperations();
                ozellikListesi=fileOperations.ExtractAttributes(fileopen,valuesMap,hashmapkeys);
                ozelliklerJList.setListData(ozellikListesi);
                veriler=fileOperations.getDatas(fileopen,valuesMap);     
            }catch(Exception e){
                
            }
            
        }else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_FileOpenMenuActionPerformed

    private void Button_ClassifywithKNNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ClassifywithKNNMouseClicked
       
        List<String> Unclassified_test=new ArrayList<>();
        List<String> Classified_test=new ArrayList<>();
        List<Integer> hatali_indexler=new ArrayList<>();
        
        KNN knn=new KNN();
        int k=Integer.parseInt(Combox_ValueOfK.getSelectedItem().toString());
        
        if(RadioButton_UseTrainingSet.isSelected()){ // Use Training Set İşlemleri
            resultList.clear();
            Unclassified_test.clear();
            Classified_test.clear();
            hatali_indexler.clear();
            
            Unclassified_test=veriler;
            Classified_test=knn.classify_with_KNN(k, veriler, Unclassified_test, valuesMap, hashmapkeys);
            hatali_indexler=knn.getHatali_indexler(Unclassified_test, Classified_test);
            resultList=knn.getResultsList(veriler, Classified_test);
            resultList=knn.getwithRealClassNames(resultList, hashmapkeys);
            
        }else if(RadioButton_UseSuppliedTest.isSelected()){ // Use Supplied Test İşlemleri
            resultList.clear();
            Unclassified_test.clear();
            Classified_test.clear();
            hatali_indexler.clear();
            
            Unclassified_test=veriler_suppliedTest;
            Classified_test=knn.classify_with_KNN(k, veriler, Unclassified_test, valuesMap_suppliedtest, hashmapkeys_suppliedtest);
            hatali_indexler=knn.getHatali_indexler(Unclassified_test, Classified_test);
            resultList=knn.getResultsList(Unclassified_test, Classified_test);
            resultList=knn.getwithRealClassNames(resultList, hashmapkeys);
            
        }else if(RadioButton_CrossValidation.isSelected()){ // Cross Validation İşlemleri
            resultList.clear();
            Unclassified_test.clear();
            Classified_test.clear();
            hatali_indexler.clear();
            
            int foldvalue=Integer.parseInt(Fold_Combobox.getSelectedItem().toString());
            resultList=knn.cross_validation(foldvalue, k, veriler);
            hatali_indexler=knn.cross_validation_hataliindexler(resultList);
            resultList=knn.getwithRealClassNames(resultList, hashmapkeys);            
        }
        
        
        String[] sonucListesi=new String[resultList.size()];
        for(int i=0;i<resultList.size();i++){
            sonucListesi[i]=resultList.get(i);
        }
        
        jlisttemizle(JListResults);
        JListResults.setCellRenderer(new MyListCellThing(hatali_indexler));
        JListResults.setListData(sonucListesi);
        double success_ratio=(100.0*(sonucListesi.length-hatali_indexler.size()))/sonucListesi.length*1.0;
        
        String a=String.format("%.2f", success_ratio);
        TextField_SuccessRatio.setText(a+ " %");
    }//GEN-LAST:event_Button_ClassifywithKNNMouseClicked

    private void Button_UseSuppliedSetSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_UseSuppliedSetSelectMouseClicked
        if(RadioButton_UseSuppliedTest.isSelected()){
            int returnVal = FileChooser_SuppliedTest.showOpenDialog(this);
        
        if (returnVal == FileChooser_SuppliedTest.APPROVE_OPTION) {
            filetest=FileChooser_SuppliedTest.getSelectedFile();
            
            try{
                fileOperations_suppliedtest=new FileOperations();
                fileOperations_suppliedtest.ExtractAttributes(filetest,valuesMap_suppliedtest,hashmapkeys_suppliedtest);
                veriler_suppliedTest=fileOperations_suppliedtest.getDatas(filetest,valuesMap_suppliedtest);
                //hashmapkeys_suppliedtest=fileOperations_suppliedtest.getHashmapKeys();   
            }catch(Exception e){
                
            }
            
        }else {
            System.out.println("File access cancelled by user.");
        }
     }
        
    }//GEN-LAST:event_Button_UseSuppliedSetSelectMouseClicked

    private void Button_ClassifyNewDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ClassifyNewDataMouseClicked
        List<String> newdata=new ArrayList<>();
        List<String> classified_data=new ArrayList<>();
        
        KNN knn=new KNN();
        int k=Integer.parseInt(Combox_ValueOfK.getSelectedItem().toString());
        newdata.add(TextField_NewData.getText());
        classified_data=knn.classify_with_KNN(k, veriler, newdata, valuesMap, hashmapkeys);
        System.out.println("siniflandirilmis:"+ hashmapkeys.get(Integer.parseInt(classified_data.get(0))));
        TextField_Result.setText(hashmapkeys.get(Integer.parseInt(classified_data.get(0))-1));
    }//GEN-LAST:event_Button_ClassifyNewDataMouseClicked

    public void jlisttemizle(JList jL){
        jL.setModel(new DefaultListModel());
        DefaultListModel dlm=(DefaultListModel) jL.getModel();
        dlm.removeAllElements();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADM_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADM_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADM_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADM_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADM_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ClassifyNewData;
    private javax.swing.JButton Button_ClassifywithKNN;
    private javax.swing.JButton Button_UseSuppliedSetSelect;
    private javax.swing.JComboBox Combox_ValueOfK;
    private javax.swing.JFileChooser FileChooser_FileOpen;
    private javax.swing.JFileChooser FileChooser_SuppliedTest;
    private javax.swing.JTextArea FileContentTextArea;
    private javax.swing.JMenuItem FileExitMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem FileOpenMenu;
    private javax.swing.JComboBox Fold_Combobox;
    private javax.swing.JList JListResults;
    private javax.swing.ButtonGroup RadiGroup1;
    private javax.swing.JRadioButton RadioButton_CrossValidation;
    private javax.swing.JRadioButton RadioButton_UseSuppliedTest;
    private javax.swing.JRadioButton RadioButton_UseTrainingSet;
    private javax.swing.JTextField TextField_NewData;
    private javax.swing.JTextField TextField_Result;
    private javax.swing.JTextField TextField_SuccessRatio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JList ozelliklerJList;
    // End of variables declaration//GEN-END:variables
}
